import Head from 'next/head'
import { useController, useForm, UseControllerProps, FieldValues } from 'react-hook-form'
import { Total, FieldArray } from './components/FieldArray'

type DefaultValues = {
  firstName: string
  state: string
}

export default function Home() {
  const { handleSubmit, control } = useForm<DefaultValues>({
    defaultValues: {
      firstName: '',
      state: ''
    }
  })

  const onSubmit = (data: DefaultValues) => console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{/* <FieldArray /> */}</main>
    </>
  )
}
