import Head from 'next/head'
import { useController, useForm, UseControllerProps, FieldValues } from 'react-hook-form'
import { FieldArray } from './components/FieldArray'
import { SelectField } from './components/SelectedField'

type DefaultValues = {
  firstName: string
  state: string
}

const options = [
  {
    id: 'dds',
    option: 1
  }
]

export default function Home() {
  const { handleSubmit, control } = useForm<DefaultValues>({
    defaultValues: {
      firstName: '',
      state: ''
    }
  })

  const onSubmit = (data: DefaultValues) => console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <SelectField control={control} name="firstName" options={options} />
          <button type="submit">Enviar</button>
        </form>
      </main>
    </>
  )
}
